# Generated by Django 4.2.6 on 2023-10-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Audit Universe',
                'verbose_name_plural': 'Audit Universe',
                'unique_together': {('company', 'country', 'region', 'city', 'branch', 'division', 'department')},
            },
        ),
    ]
