# Generated by Django 4.2.6 on 2023-10-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
            options={
                'verbose_name': 'Information Required',
                'verbose_name_plural': 'Information Required',
            },
        ),
        migrations.CreateModel(
            name='ManagementComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_by', models.CharField(blank=True, choices=[('Management', 'Management'), ('Auditor', 'Auditor')], max_length=100, null=True)),
                ('comments', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Management Comments',
                'verbose_name_plural': 'Management Comments',
            },
        ),
    ]
