# Generated by Django 4.2.6 on 2023-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork2', '0002_chatmessage_informationrequired_and_more'),
        ('fieldwork_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informationrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Information Request',
                'verbose_name_plural': 'Information Requests',
            },
        ),
        migrations.DeleteModel(
            name='InformationRequired',
        ),
    ]
