# Generated by Django 4.2.6 on 2023-11-14 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_plan_setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditor',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='auditor_profiles/'),
        ),
        migrations.CreateModel(
            name='Auditee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='auditee_profiles/')),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditee',
                'verbose_name_plural': 'Auditees',
            },
        ),
    ]
