# Generated by Django 4.2.6 on 2023-11-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldwork2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformationRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='information_required/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('Chat_room', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Information Required',
                'verbose_name_plural': 'Information Required',
            },
        ),
        migrations.AddField(
            model_name='auditporgram',
            name='auditee_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditporgram',
            name='create_chatroom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
