# Generated by Django 4.2.6 on 2023-11-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_plan_setup', '0001_initial'),
        ('fieldwork2', '0002_chatmessage_informationrequired_and_more'),
        ('fieldwork_setup', '0002_informationrequest_delete_informationrequired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditporgram',
            name='information_required',
            field=models.ManyToManyField(blank=True, to='fieldwork_setup.informationrequest'),
        ),
        migrations.AddField(
            model_name='informationrequired',
            name='audit_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='fieldwork2.auditinprogress'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_plan_setup.auditor'),
        ),
        migrations.AddField(
            model_name='auditporgram',
            name='uploaded_requirements',
            field=models.ManyToManyField(blank=True, to='fieldwork2.informationrequired'),
        ),
    ]
