# Generated by Django 4.2.6 on 2023-10-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_frequency', models.CharField(max_length=100, unique=True)),
                ('control_frequency_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Control Frequency',
                'verbose_name_plural': 'Control Frequency',
                'ordering': ['control_frequency'],
            },
        ),
        migrations.CreateModel(
            name='ControlOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_owner', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Control Owner',
                'verbose_name_plural': 'Control Owner',
                'ordering': ['control_owner'],
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Function',
                'verbose_name_plural': 'Function',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MajorProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Major Process',
                'verbose_name_plural': 'Major Process',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResponseStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_strategy', models.CharField(max_length=100, unique=True)),
                ('response_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Response Strategy',
                'verbose_name_plural': 'Response Strategy',
                'ordering': ['response_strategy'],
            },
        ),
        migrations.CreateModel(
            name='RiskOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_owner', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Risk Owner',
                'verbose_name_plural': 'Risk Owner',
                'ordering': ['risk_owner'],
            },
        ),
        migrations.CreateModel(
            name='StrategicImportanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Strategic Importance List',
                'verbose_name_plural': 'Strategic Importance List',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sub Process',
                'verbose_name_plural': 'Sub Process',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_control', models.CharField(max_length=100, unique=True)),
                ('type_of_control_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type of Control',
                'verbose_name_plural': 'Type of Control',
                'ordering': ['type_of_control'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_risk', models.CharField(max_length=100, unique=True)),
                ('risk_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type of Risk',
                'verbose_name_plural': 'Type of Risk',
                'ordering': ['type_of_risk'],
            },
        ),
    ]
