# Generated by Django 4.2.6 on 2023-10-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_universe', '0001_initial'),
        ('risk_assessment_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('strategic_importance', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100, null=True)),
                ('strategic_importance_score', models.IntegerField(blank=True, default=0, null=True)),
                ('strategic_objective', models.TextField(blank=True, max_length=100, null=True)),
                ('audit_universe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_universe.audituniverse')),
                ('strategic_importance_in_next_1_to_5_years', models.ManyToManyField(blank=True, to='risk_assessment_setup.strategicimportancelist')),
            ],
            options={
                'verbose_name': 'Strategic Importance',
                'verbose_name_plural': 'Strategic Importance',
                'unique_together': {('audit_universe', 'strategic_objective')},
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('division', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('risk_details', models.TextField(null=True)),
                ('impact', models.CharField(choices=[('Rare', 'Rare'), ('Unlikely', 'Unlikely'), ('Likely', 'Likely'), ('Possible', 'Possible'), ('Certain', 'Certain')], max_length=100, null=True)),
                ('likelihood', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=100, null=True)),
                ('risk_score', models.CharField(blank=True, max_length=100, null=True)),
                ('overall_inherent_risk_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('response_action', models.TextField(blank=True, null=True)),
                ('control_design', models.CharField(blank=True, choices=[('Very Strong', 'Very Strong'), ('Strong', 'Strong'), ('Medium', 'Medium'), ('Weak', 'Weak'), ('Very Weak', 'Very Weak')], max_length=100, null=True)),
                ('effectiveness', models.CharField(blank=True, choices=[('Highly Effective', 'Highly Effective'), ('Effective', 'Effective'), ('Moderately Effective', 'Moderately Effective'), ('Partially Effective', 'Partially Effective'), ('Ineffective', 'Ineffective')], max_length=100, null=True)),
                ('control_score', models.CharField(blank=True, max_length=100, null=True)),
                ('overall_control_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('residual_score_total', models.CharField(blank=True, max_length=100, null=True)),
                ('residual_score', models.IntegerField(blank=True, default=0, null=True)),
                ('residual_risk_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('audit_universe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_universe.audituniverse')),
                ('control_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_assessment_setup.controlfrequency')),
                ('control_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_assessment_setup.controlowner')),
                ('function', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_assessment_setup.function')),
                ('major_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_assessment_setup.majorprocess')),
                ('response_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_assessment_setup.responsestrategy')),
                ('risk_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_assessment_setup.riskowner')),
                ('sub_process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_assessment_setup.subprocess')),
                ('type_of_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_assessment_setup.typeofcontrol')),
                ('type_of_risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk_assessment_setup.typeofrisk')),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risk',
                'unique_together': {('audit_universe', 'function', 'major_process', 'sub_process', 'risk_details')},
            },
        ),
    ]
