# Generated by Django 4.2.6 on 2023-11-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment_setup', '0001_initial'),
        ('risk_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='impact',
            field=models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='likelihood',
            field=models.CharField(choices=[('Rare', 'Rare'), ('Unlikely', 'Unlikely'), ('Likely', 'Likely'), ('Possible', 'Possible'), ('Certain', 'Certain')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='type_of_risk',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='type_of_risk',
            field=models.ManyToManyField(blank=True, null=True, to='risk_assessment_setup.typeofrisk'),
        ),
    ]
