# Generated by Django 4.2.6 on 2023-10-07 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_plan_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], null=True)),
                ('level', models.CharField(choices=[('company', 'company'), ('country', 'country'), ('region', 'region'), ('city', 'city'), ('branch', 'branch'), ('division', 'division'), ('department', 'department'), ('function', 'function'), ('major_process', 'major_process'), ('sub_process', 'sub_process')], max_length=100, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Audit Year',
                'verbose_name_plural': 'Audit Year',
                'unique_together': {('year', 'level')},
            },
        ),
        migrations.CreateModel(
            name='AuditDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_year', models.IntegerField(blank=True, null=True)),
                ('level_type', models.CharField(blank=True, max_length=100, null=True)),
                ('level_name', models.CharField(blank=True, max_length=100, null=True)),
                ('residual_score', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('risk_assessment', models.CharField(blank=True, max_length=10, null=True)),
                ('risk_assessment_by_auditor', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100, null=True)),
                ('strategic_importance_score', models.CharField(blank=True, max_length=100, null=True)),
                ('count_2', models.IntegerField(blank=True, default=0, null=True)),
                ('strategic_importance', models.CharField(blank=True, max_length=100, null=True)),
                ('strategic_importance_by_auditor', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=100, null=True)),
                ('last_audit', models.CharField(blank=True, choices=[('Less than 6', 'Less than 6'), ('6 to 12', '6 to 12'), ('12 to 18', '12 to 18'), ('18 to 24', '18 to 24'), ('More than 24', 'More than 24')], max_length=100, null=True)),
                ('total_priority_score', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('number_of_hours_per_day', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_days', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('select_for_audit', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('number_of_auditor', models.IntegerField(blank=True, default=0, null=True)),
                ('total_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_audit_process', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100, null=True)),
                ('name_of_auditor', models.ManyToManyField(blank=True, to='audit_plan_setup.auditor')),
                ('start_audit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_plan.startaudit')),
            ],
            options={
                'verbose_name': 'Start Audit Planning',
                'verbose_name_plural': 'Start Audit Planning',
            },
        ),
    ]
